sonar.organization=caio-martin
sonar.projectKey=Caio-Martin_Portifolio
sonar.projectName=Portifolio
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=.git/**,.github/**,node_modules/**,cypress/**,scripts/**,README.md
sonar.inclusions=**/*.html,**/*.css,**/*.js
sonar.coverage.exclusions=**/*
